import 'package:flutter/material.dart';


class Product {
  final String title;
  final String description;
  final String image;
  final String review;
  final String seller;
  final int price;
  final List<Color> colors;
  final String category;
  final double rate;
   int quantity;

  Product({
    required this.title,
    required this.description,
    required this.image,
    required this.review,
    required this.seller,
    required this.price,
    required this.colors,
    required this.category,
    required this.rate,
    required this.quantity,
  });
}



  final List<Product> all = [
    Product(
      title: "Stylo Shoes",
      description: "Trendy women's shoes by Stylo. Stylish and comfortable.",
      image: "images/slider (4).jpg",
      price: 95,
      seller: "Stylo",
      colors: [Colors.pink, Colors.black],
      category: "Shoes",
      review: "(70 Reviews)",
      rate: 4.5,
      quantity: 1,
    ),
    Product(
      title: "Smart Watch",
      description:
      "Elegant meets functional with this stylish women’s smartwatch."
          "Track your fitness, monitor health, and stay connected on the go."
          "Sleek design, customizable faces, and all-day battery life in one smart accessory.",
      image: "images/smart.jpeg",
      price: 55,
      seller: "Ram Das",
      colors: [
        Colors.black,
        Colors.orange,
        Colors.pink,
      ],
      category: "Watches",
      review: "(100 Reviews)",
      rate: 4.6,
      quantity: 1,
    ),
    Product(
      title: "Gucci Handbag",
      description: "Elegant and stylish Gucci handbag with premium leather finish.",
      image: "images/bag.jpeg",
      price: 250,
      seller: "Gucci Official",
      colors: [Colors.brown, Colors.black],
      category: "Bags",
      review: "(85 Reviews)",
      rate: 4.8,
      quantity: 1,
    ),

    Product(
      title: "Summer Hat",
      description: "Lightweight and breathable hat, perfect for sunny days.",
      image: "images/hat.jpeg",
      price: 40,
      seller: "SunnyStyle",
      colors: [Colors.grey, Colors.white],
      category: "Hats",
      review: "(54 Reviews)",
      rate: 4.3,
      quantity: 1,
    ),

    Product(
      title: "Cotton Shirt",
      description: "Comfortable cotton shirt for daily wear with a smart casual look.",
      image: "images/shirt.jpeg",
      price: 65,
      seller: "Shirt Hub",
      colors: [Colors.white, Colors.blue],
      category: "Shirts",
      review: "(120 Reviews)",
      rate: 4.6,
      quantity: 1,
    ),
    Product(
      title: "Woman Sweater",
      description:
      "Stay cozy and stylish with this soft, warm women’s sweater."
          "Perfect for layering in cooler weather, with a flattering and comfy fit."
          "Made from quality fabric for all-day comfort and timeless charm.",
      image: "images/sweater.jpeg",
      price: 120,
      seller: "Joy Store",
      colors: [
        Colors.brown,
        Colors.deepPurple,
        Colors.pink,
      ],
      category: "Sweaters",
      review: "(32 Reviews)",
      rate: 4.5,
      quantity: 1,
    ),

  Product(
    title: "Wireless Headphones",
    description:
    "Experience high-quality, wireless sound with these stylish Bluetooth headphones."
    "Enjoy up to 20 hours of battery life and seamless connectivity on the go."
    "Designed for comfort and clarity, perfect for music, calls, and more.",
    image: "images/headphone.jpeg",
    price: 120,
    seller: "TuneNest",
    colors: [
      Colors.black,
      Colors.blue,
      Colors.orange,
    ],
    category: "Headphones",
    review: "(320 Reviews)",
    rate: 4.8,
    quantity: 1,
  ),


  Product(
    title: "Men's Jacket",
    description:
    "Upgrade your style with this rugged yet refined men’s jacket."
    "Designed for comfort and warmth, perfect for everyday wear or outdoor adventures."
    "Durable fabric, smart fit, and timeless look all in one layer.",
    image: "images/mens.jpeg",
    price: 150,
    seller: "Urban Outfitters",
    colors: [
      Colors.grey,
      Colors.black,
      Colors.blueGrey,
    ],
    category: "Mens Wear",
    review: "(210 Reviews)",
    rate: 4.7,
    quantity: 1,
  ),



];

final List<Product> Shoes = [
  Product(
    title: "Stylo Shoes",
    description: "Trendy women's shoes by Stylo. Stylish and comfortable.",
    image: "images/shoe (1).png",
    price: 95,
    seller: "Stylo",
    colors: [Colors.pink, Colors.black],
    category: "Shoes",
    review: "(70 Reviews)",
    rate: 4.5,
    quantity: 1,
  ),
  Product(
    title: "Women's Casual Shoes",
    description: "Lightweight and comfortable casual shoes for daily use.",
    image: "images/shoe (2).jpg",
    price: 85,
    seller: "WalkWay",
    colors: [Colors.red, Colors.grey],
    category: "Shoes",
    review: "(55 Reviews)",
    rate: 4.4,
    quantity: 1,
  ),
  Product(
    title: "Sports Shoes",
    description: "Durable sports shoes with strong grip and breathable mesh.",
    image: "images/shoe (3).jpg",
    price: 110,
    seller: "Athletix",
    colors: [Colors.blue, Colors.black],
    category: "Shoes",
    review: "(98 Reviews)",
    rate: 4.6,
    quantity: 1,
  ),
  Product(
    title: "Formal Leather Shoes",
    description: "Classic leather shoes ideal for business or formal wear.",
    image: "images/shoe (4).jpg",
    price: 140,
    seller: "Oxford",
    colors: [Colors.brown, Colors.black],
    category: "Shoes",
    review: "(67 Reviews)",
    rate: 4.7,
    quantity: 1,
  ),
  Product(
    title: "Canvas Sneakers",
    description: "Trendy canvas sneakers great for casual outfits and comfort.",
    image: "images/shoe (5).jpg",
    price: 60,
    seller: "SneakerX",
    colors: [Colors.red, Colors.pinkAccent],
    category: "Shoes",
    review: "(80 Reviews)",
    rate: 4.3,
    quantity: 1,
  ),
  Product(
    title: "High Heels",
    description: "Elegant high heels for parties and formal occasions.",
    image: "images/shoe (6).jpg",
    price: 130,
    seller: "Glam Steps",
    colors: [Colors.black, Colors.pinkAccent],
    category: "Shoes",
    review: "(74 Reviews)",
    rate: 4.4,
    quantity: 1,
  ),
  Product(
    title: "Kids Running Shoes",
    description: "Light, flexible, and colorful shoes for active kids.",
    image: "images/shoe (7).jpg",
    price: 50,
    seller: "TinySteps",
    colors: [Colors.green, Colors.yellow],
    category: "Shoes",
    review: "(45 Reviews)",
    rate: 4.2,
    quantity: 1,
  ),
];
final List<Product> Watches = [
  Product(
    title: "Smart Watch",
    description:
    "Elegant meets functional with this stylish women’s smartwatch. Track your fitness, monitor health, and stay connected on the go. Sleek design, customizable faces, and all-day battery life in one smart accessory.",
    image: "images/watch (1).jpg",
    price: 55,
    seller: "Ram Das",
    colors: [Colors.black, Colors.orange, Colors.pink],
    category: "Watches",
    review: "(100 Reviews)",
    rate: 4.6,
    quantity: 1,
  ),
  Product(
    title: "Men’s Digital Watch",
    description:
    "Rugged and reliable digital watch with stopwatch, timer, and backlight features. Water-resistant and ideal for sports.",
    image: "images/watch (2).jpg",
    price: 75,
    seller: "Timex",
    colors: [Colors.grey, Colors.black],
    category: "Watches",
    review: "(89 Reviews)",
    rate: 4.5,
    quantity: 1,
  ),
  Product(
    title: "Classic Analog Watch",
    description:
    "Stylish analog watch with leather strap. Timeless design suitable for both casual and formal wear.",
    image: "images/watch (3).jpg",
    price: 120,
    seller: "Rolex",
    colors: [Colors.brown, Colors.black],
    category: "Watches",
    review: "(145 Reviews)",
    rate: 4.9,
    quantity: 1,
  ),
  Product(
    title: "Fitness Tracker Watch",
    description:
    "Track steps, heart rate, sleep, and more with this lightweight fitness tracker. Ideal for everyday health monitoring.",
    image: "images/watch (4).jpg",
    price: 65,
    seller: "FitPro",
    colors: [Colors.blue, Colors.purple],
    category: "Watches",
    review: "(102 Reviews)",
    rate: 4.4,
    quantity: 1,
  ),
];
final List<Product> Bags = [
  Product(
    title: "Gucci Handbag",
    description: "Elegant and stylish Gucci handbag with premium leather finish.",
    image: "images/bag (1).jpg",
    price: 250,
    seller: "Gucci Official",
    colors: [Colors.brown, Colors.black],
    category: "Bags",
    review: "(85 Reviews)",
    rate: 4.8,
    quantity: 1,
  ),
  Product(
    title: "Leather Crossbody Bag",
    description: "Compact and sleek crossbody bag with adjustable strap and elegant finish.",
    image: "images/bag (2).jpg",
    price: 120,
    seller: "Zara",
    colors: [Colors.black, Colors.grey],
    category: "Bags",
    review: "(65 Reviews)",
    rate: 4.5,
    quantity: 1,
  ),
  Product(
    title: "Travel Backpack",
    description: "Spacious and durable backpack for travel or daily use. Multiple compartments.",
    image: "images/bag (3).jpg",
    price: 90,
    seller: "TravelPro",
    colors: [Colors.blue, Colors.yellowAccent],
    category: "Bags",
    review: "(110 Reviews)",
    rate: 4.6,
    quantity: 1,
  ),
  Product(
    title: "Tote Bag",
    description: "Stylish canvas tote bag perfect for shopping, work, or casual outings.",
    image: "images/bag (4).webp",
    price: 45,
    seller: "EcoCarry",
    colors: [Colors.grey, Colors.green],
    category: "Bags",
    review: "(50 Reviews)",
    rate: 4.3,
    quantity: 1,
  ),
];
final List<Product> Hats = [
  Product(
    title: "Summer Hat",
    description: "Lightweight and breathable hat, perfect for sunny days.",
    image: "images/hat (1).jpg",
    price: 40,
    seller: "SunnyStyle",
    colors: [Colors.grey, Colors.yellowAccent],
    category: "Hats",
    review: "(54 Reviews)",
    rate: 4.3,
    quantity: 1,
  ),
  Product(
    title: "Fedora Hat",
    description: "Classic and stylish fedora hat for a vintage look.",
    image: "images/hat (2).jpg",
    price: 70,
    seller: "ClassicWear",
    colors: [Colors.black, Colors.brown],
    category: "Hats",
    review: "(120 Reviews)",
    rate: 4.5,
    quantity: 1,
  ),
  Product(
    title: "Baseball Cap",
    description: "Casual and sporty baseball cap, perfect for outdoor activities.",
    image: "images/hat (3).jpg",
    price: 30,
    seller: "SportyFit",
    colors: [Colors.blue, Colors.red],
    category: "Hats",
    review: "(88 Reviews)",
    rate: 4.2,
    quantity: 1,
  ),
  Product(
    title: "Wool Beanie",
    description: "Warm and cozy wool beanie, ideal for cold weather.",
    image: "images/hat (4).webp",
    price: 25,
    seller: "WarmWear",
    colors: [Colors.red, Colors.black],
    category: "Hats",
    review: "(65 Reviews)",
    rate: 4.4,
    quantity: 1,
  ),
];
final List<Product> Shirts = [
  Product(
    title: "Cotton Shirt",
    description: "Comfortable cotton shirt for daily wear with a smart casual look.",
    image: "images/shirt (1).jpg",
    price: 65,
    seller: "Shirt Hub",
    colors: [Colors.brown, Colors.blue],
    category: "Shirts",
    review: "(120 Reviews)",
    rate: 4.6,
    quantity: 1,
  ),
  Product(
    title: "Linen Shirt",
    description: "Lightweight and breathable linen shirt for a relaxed, stylish look.",
    image: "images/shirt (4).webp",
    price: 75,
    seller: "Linen Comfort",
    colors: [Colors.blue, Colors.green],
    category: "Shirts",
    review: "(110 Reviews)",
    rate: 4.7,
    quantity: 1,
  ),
  Product(
    title: "Plaid Shirt",
    description: "Classic plaid shirt with a modern fit, perfect for casual occasions.",
    image: "images/shirt (5).jpg",
    price: 60,
    seller: "PlaidStyle",
    colors: [Colors.red, Colors.blue],
    category: "Shirts",
    review: "(80 Reviews)",
    rate: 4.4,
    quantity: 1,
  ),
  Product(
    title: "Slim Shirt",
    description: "Smart and stylish slim-fit shirt, perfect for formal or semi-formal occasions.",
    image: "images/shirt (6).jpg",
    price: 85,
    seller: "SlimStyle",
    colors: [Colors.black, Colors.grey],
    category: "Shirts",
    review: "(95 Reviews)",
    rate: 4.8,
    quantity: 1,
  ),
];
final List<Product> Sweaters = [
  Product(
    title: "Chunky Sweater",
    description: "Warm and cozy chunky knit sweater for the colder months.",
    image: "images/sweater (1).webp",
    price: 120,
    seller: "CozyWear",
    colors: [Colors.brown, Colors.grey],
    category: "Sweaters",
    review: "(110 Reviews)",
    rate: 4.6,
    quantity: 1,
  ),
  Product(
    title: "Cashmere Sweater",
    description: "Luxurious and soft cashmere sweater, perfect for a premium feel.",
    image: "images/sweater (2).jpg",
    price: 200,
    seller: "CashmereDelight",
    colors: [Colors.black, Colors.blueGrey],
    category: "Sweaters",
    review: "(80 Reviews)",
    rate: 4.8,
    quantity: 1,
  ),
  Product(
    title: "V-neck Sweater",
    description: "Stylish V-neck sweater for a chic, everyday look.",
    image: "images/sweater (3).jpg",
    price: 90,
    seller: "FashionHub",
    colors: [Colors.blue, Colors.green],
    category: "Sweaters",
    review: "(95 Reviews)",
    rate: 4.5,
    quantity: 1,
  ),
  Product(
    title: "Wool Sweater",
    description: "Soft wool sweater, perfect for layering in the colder season.",
    image: "images/sweater (4).jpg",
    price: 140,
    seller: "WoolCo",
    colors: [Colors.red, Colors.orange],
    category: "Sweaters",
    review: "(70 Reviews)",
    rate: 4.7,
    quantity: 1,
  ),
];
final List<Product> Headphone = [
  Product(
    title: "NoiseCancel Headphones",
    description: "High-quality noise-cancelling headphones for an immersive audio experience.",
    image: "images/headphon (1).jpg",
    price: 180,
    seller: "SoundTech",
    colors: [Colors.black, Colors.orange],
    category: "Headphones",
    review: "(250 Reviews)",
    rate: 4.7,
    quantity: 1,
  ),
  Product(
    title: "Bluetooth Headphones",
    description: "Comfortable over-ear Bluetooth headphones with up to 20 hours of battery life.",
    image: "images/headphon (2).webp",
    price: 120,
    seller: "TuneNest",
    colors: [Colors.blue, Colors.black],
    category: "Headphones",
    review: "(320 Reviews)",
    rate: 4.6,
    quantity: 1,
  ),
  Product(
    title: "Sports Earbuds",
    description: "Compact and sweat-proof wireless earbuds designed for workouts and outdoor use.",
    image: "images/headphon (3).webp",
    price: 75,
    seller: "ActiveSound",
    colors: [Colors.green, Colors.indigo],
    category: "Headphones",
    review: "(150 Reviews)",
    rate: 4.5,
    quantity: 1,
  ),
  Product(
    title: "Gaming Headset",
    description: "Premium gaming headset with surround sound and a built-in microphone for clear communication.",
    image: "images/headphon (4).webp",
    price: 160,
    seller: "GameMaster",
    colors: [Colors.red, Colors.black],
    category: "Headphones",
    review: "(400 Reviews)",
    rate: 4.8,
    quantity: 1,
  ),
];
final List<Product> MensWear = [
  Product(
    title: "Leather Jacket",
    description: "Stylish leather bomber jacket for a bold and edgy look.",
    image: "images/wear (4).jpg",
    price: 200,
    seller: "Urban Outfitters",
    colors: [Colors.black, Colors.brown],
    category: "Mens Wear",
    review: "(150 Reviews)",
    rate: 4.7,
    quantity: 1,
  ),
  Product(
    title: "Slim Jeans",
    description: "Comfortable and trendy slim fit jeans for a modern casual look.",
    image: "images/wear (1).jpg",
    price: 90,
    seller: "Denim Co.",
    colors: [Colors.blue, Colors.cyan],
    category: "Mens Wear",
    review: "(210 Reviews)",
    rate: 4.5,
    quantity: 1,
  ),
  Product(
    title: "Polo T-shirt",
    description: "Classic polo T-shirt for a smart casual style. Available in various colors.",
    image: "images/wear (2).jpg",
    price: 50,
    seller: "CasualWear",
    colors: [Colors.white, Colors.blue],
    category: "Mens Wear",
    review: "(180 Reviews)",
    rate: 4.6,
    quantity: 1,
  ),
  Product(
    title: "Chinos Pants",
    description: "Versatile chinos pants, perfect for both casual and semi-formal occasions.",
    image: "images/wear (3).jpg",
    price: 80,
    seller: "StyleMart",
    colors: [Colors.pinkAccent, Colors.black],
    category: "Mens Wear",
    review: "(95 Reviews)",
    rate: 4.4,
    quantity: 1,
  ),
];









